name: Run RegFinder

on:
  push:
  workflow_dispatch: # Allow manual runs

jobs:
  run-regfinder:
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download regfinder binary
      run: |
        wget https://github.com/matejsmycka/regfinder/raw/main/build/regfinder.elf
        chmod +x ./regfinder.elf

    - name: Download general.txt regex file
      run: |
        wget https://raw.githubusercontent.com/matejsmycka/regfinder/main/regex_dir/general.txt

    - name: Run RegFinder
      run: |
        ./regfinder.elf -d . -f general.txt
