name: Run RegFinder

on:
  push:
  workflow_dispatch: # Allow manual runs

jobs:
  run-regfinder:
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create tools directory in /tmp
      run: mkdir /tmp/tools

    - name: Download regfinder binary
      run: |
        wget -O /tmp/tools/regfinder.elf https://github.com/matejsmycka/regfinder/raw/main/build/regfinder.elf
        chmod +x /tmp/tools/regfinder.elf

    - name: Download general.txt regex file
      run: wget -O /tmp/tools/general.txt https://raw.githubusercontent.com/matejsmycka/regfinder/main/regex_dir/general.txt

    - name: Run RegFinder
      run: |
        /tmp/tools/regfinder.elf -d . -f /tmp/tools/general.txt
