name: Semgrep CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Semgrep scan
        run: semgrep scan . --config "python" --metrics=off
