name: semgrep 
on:
  push:
jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Semgrep scan
        run: semgrep scan . --config "p/python" --metrics=off --error
